### ISSUE TITLE
Unknown version 2022.3.0dev6 when running task-rest

### ISSUE THREAD

**Issue by acionca** [TheAxonLab/HCPh-fMRI-tasks#40]
I tried installing psychopy (which worked well), then I tried to test it and run the `rest` expriement and I get this type of error:
``` python
Traceback (most recent call last):
  File "/home/acionca/Documents/code/psychopy/psychopy/app/builder/builder.py", line 1249, in runFile
    self.app.runner.panel.runLocal(event)
  File "/home/acionca/Documents/code/psychopy/psychopy/app/runner/runner.py", line 749, in runLocal
    generateScript(experimentPath=currentFile.replace('.psyexp', '_lastrun.py'),
  File "/home/acionca/Documents/code/psychopy/psychopy/scripts/psyexpCompile.py", line 86, in generateScript
    raise LegacyScriptError(
psychopy.scripts.psyexpCompile.LegacyScriptError: Error: Script compile exited with code 1. Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/acionca/Documents/code/psychopy/psychopy/scripts/psyexpCompile.py", line 237, in <module>
    compileScript(args.infile, args.version, args.outfile)
  File "/home/acionca/Documents/code/psychopy/psychopy/scripts/psyexpCompile.py", line 226, in compileScript
    version = _setVersion(version)
  File "/home/acionca/Documents/code/psychopy/psychopy/scripts/psyexpCompile.py", line 125, in _setVersion
    useVersion(version)
  File "/home/acionca/Documents/code/psychopy/psychopy/tools/versionchooser.py", line 205, in useVersion
    raise ValueError(msg.format(requestedVersion))
ValueError: Unknown version `2022.3.0dev6`
```

Is it something to be expected ?

**Comment by esavary** [comment]
I think it could be due to using the wrong Psychopy version. Check the version you installed, and in the Psychopy builder settings, you'll see an option called 'Psychopy version.' Normally, you can choose the right one there.
